version: "3.3"
services:
  pgrouting:
    container_name: pgrouting
    restart: always
    image: pgrouting/pgrouting:13-3.0-3.1.0
    volumes:
      - ./containers/pgrouting/data:/var/lib/postgresql/data
      - ./containers/pgrouting/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=tttBBB777
    networks:
      - pgrouting-front
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 20s
      timeout: 5s
      retries: 5

  app:
    container_name: app
    environment:
      - POSTGRES_PASSWORD=tttBBB777
    ports: 
      - 1769:1769
    build:
      context: containers/app
    depends_on: 
      pgrouting:
        condition: service_healthy
    command: "/usr/bin/python3 app.py"
    networks:
      - pgrouting-front


networks:
  pgrouting-front:
    driver: bridge
