version: "3.3"
services:
  pgrouting:
    container_name: pgrouting
    restart: always
    build:
      context: containers/pgrouting
    volumes:
      - ./containers/pgrouting/data:/var/lib/postgresql/data
      - ./containers/pgrouting/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./containers/pgrouting/osm:/osm
    environment:
      - POSTGRES_PASSWORD=tttBBB777
    networks:
      - pgrouting-front

  pgadmin:
    container_name: pgrouting-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: vazheningleb@gmail.com
      PGADMIN_DEFAULT_PASSWORD: tttBBB777
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    volumes:
      - ./containers/pgadmin/data/:/var/lib/pgadmin
    ports:
      - "5051:5050"
    networks:
      - pgrouting-front
    restart: unless-stopped
    depends_on:
      - pgrouting

networks:
  pgrouting-front:
    driver: bridge